### ISSUE TITLE
unexpected unclosed action in parenthesized pipeline

### ISSUE THREAD

**Issue by gary094** [chipzoller/hugo-clarity#282] opened 2022-04-03 20:06 UTC
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [X] Read the README.md
- [x] Have the extended version of Hugo installed
- [X] Used the exampleSite's config.toml as a reference
- [ ] I have included my repository link. Instead of pasting long snippets here.

**Describe the bug**

Just tried to update the submodule and rebuilt my static site however I receive the following error immediately while building.

`Error: add site dependencies: load resources: loading templates: "/home/user/hugo/blog/themes/hugo-clarity/layouts/_default/_markup/render-image.html:60:1": parse failed: template: _default/_markup/render-image.html:60: unexpected unclosed action in parenthesized pipeline`

This can be reproduced using the commands in the README

```
hugo new site yourSiteName
cd yourSiteName
git init
git submodule add https://github.com/chipzoller/hugo-clarity themes/hugo-clarity
cp -a themes/hugo-clarity/exampleSite/* .
```

> Avoid long-winded descriptions

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2 Uma, hugo version v0.68.3, tested as well with Debian 11 with hugo version v0.80.0

**Comment by rootwork** [comment] 2022-04-06 23:23
@gary094 Those Hugo versions are pretty old, can you try with something more recent? https://github.com/gohugoio/hugo/releases

We have been working on that file recently so it's possible there is a bug, just want to rule out Hugo version issues.

**Comment by gary094** [comment] 2022-04-10 14:56
I finally came around to my arch linux box and yes indeed with hugo version v0.96.0+extended the site can be build just fine.

Since version v0.80.0 is present in the most recent debian 11 maybe it would be good to take a look into this issue?

**Comment by rootwork** [comment] 2022-05-17 21:27
I confirmed that 0.80.0 doesn't compile the site. I can fix "unexpected unclosed action in parenthesized pipeline" by making the code less readable, changing this:

```
{{- partial "figure" (
  dict
    "file" $file
    "image" $image
    "diskPath" $.Page.File.Dir
    "webPath" $.Page.RelPermalink
    "alt" $alt
    "cap" $cap
    "classes" ($scratch.Get "classes")
    "bundle" $bundle
) -}}
```

to this:

```
{{- partial "figure" (dict "file" $file "image" $image "diskPath" $.Page.File.Dir "webPath" $.Page.RelPermalink "alt" $alt "cap" $cap "classes" ($scratch.Get "classes") "bundle" $bundle) -}}
```

in two files (`render-image.html` and `image.html`). But then 0.80.0 also fails on `{{- $image = resources.GetRemote $file -}}`, which we use in both places to allow people to pull in remote images and use them as local images. The `GetRemote` method wasn't added to the `resources` function until [0.91.0](https://github.com/gohugoio/hugo/commit/22ef5da20d1685dfe6aff3bd9364c9b1f1d0d8f8) (and not documented until [0.93](https://github.com/gohugoio/hugo/commit/d706529720b3b2ccb99719ccd578062ca25a0cc2)).

So supporting v0.80.0 would mean ripping that part out.

I'm sympathetic to supporting older versions -- I'm on Linux Mint (Ubuntu/Debian) and the default that gets installed from my repo is 0.68! (Incidentally it looks like the Arch repo is [now installing 0.98.0](https://archlinux.org/packages/community/x86_64/hugo/).) But since users of Hugo Clarity already need to [make sure](https://github.com/chipzoller/hugo-clarity#prerequisites) they're installing the extended version, I don't think it would be unreasonable to also give them a minimum version.

So ultimately I think I'm going to mark this as invalid (really wontfix), but I'll leave it open for a bit for any further feedback.

**Comment by gary094** [comment] 2022-05-18 18:40
Thanks for looking into this!

For me it is perfectly fine to leave it as it is, since I have the possibility to just compile my website on arch and copy /public over to my webserver.

**Comment by onweru** [comment] 2022-05-18 20:26
@rootwork, maybe we should update the min version to 0.91 https://github.com/chipzoller/hugo-clarity/blob/616b44986438752406ac579e620e35b1bab1cd50/theme.toml#L9.

**Comment by rootwork** [comment] 2022-05-18 21:16
D'oh. I'll add that to #307.

**Comment by onweru** [comment] 2022-05-18 21:18
> D'oh. I'll add that to #307.

Just saw that earlier. Thank you 😄

**Closed** 2022-05-18 21:18 UTC
Labels: invalid
