### ISSUE TITLE
The feature image caption is not displayed

### ISSUE THREAD

**Issue by georgew509** [chipzoller/hugo-clarity#296] opened 2022-05-07 22:37 UTC
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [X] Read the README.md
- [X] Have the extended version of Hugo installed
- [X] Used the exampleSite's config.toml as a reference
- [X] I have included my repository link. Instead of pasting long snippets here.
         https://github.com/georgew509/clarity-aporg

I know that there has been some email about this, but I am not sure that the issue has been formally documented here. Sorry, if I missed it.

I have added featured images in page bundles to my test site. One example:
    https://altoplace.org/posts/welcome/

The feature image is working great. However, the feature caption that I added to the front matter is not displayed:

```
usePageBundles: true
featureImage: 'images/steam-locomotive-3653487_640.jpg'
featureImageAlt: "Steam locomotive."
featureImageCap: "Image by Erich Westendarp from Pixabay"
---
```

**Comment by rootwork** [comment] 2022-05-10 22:29
@georgew509 This should be fixed in #297 -- feel free to test (instructions at the bottom of that PR).

**Comment by georgew509** [comment] 2022-05-11 01:28
Hello @rootwork,

I am getting ready to head out of town for a couple of weeks, but I did get a chance to run a couple of tests.

1. The SVG image does not crash and it’s working now.  However, I noticed that for:

[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/D1D67VIRR)

“ko-fi” the ALT text is displayed under the image.

2.  The feature image caption is working now, however, the text is always left justified, but the feature image is centered.

Thanks,
George

**Comment by rootwork** [comment] 2022-05-11 18:52
@georgew509 Thanks for testing. In response to your items:

1. This is standard for the theme -- alt text is used as an image caption unless a title is provided. If don't want a caption, you can provide empty title text. [See documentation on this](https://github.com/chipzoller/hugo-clarity#image-figure-captions), although now that I'm reading it I think it could be better explained. It's also described in detail in the "Markdown Syntax Guide" page in the example site.
2. This is as designed, although because the caption feature was added separately from the featured-image feature it may not be the best design. You can open a new issue if you want to propose changing this. You can also, of course, override the CSS on your site if you'd like. The selector would be something like `.post_featured figcaption`.

**Comment by rootwork** [comment] 2022-05-11 20:49
Updated the documentation in #297 to address the less-than-clear descriptions of caption creation and usage.

**Comment by rootwork** [comment] 2022-05-16 21:54
Since the original issue appears to be solved now, I'm going to close this issue. Feel free to create new issues if you want to talk about either of the other things you mentioned.

**Closed by rootwork** 2022-05-16 21:54 UTC
Labels: bug
