### ISSUE TITLE
when running hugo server locally, css does not work due to integrity.

### ISSUE THREAD

**Issue by dstamen** [chipzoller/hugo-clarity#3] opened 2020-07-28 18:19 UTC
to get it to work locally on my mac i had to disable the data integrity lines in baseof.html

**Comment by chipzoller** [comment] 2020-07-28 18:39
I was not able to reproduce this by following both option #1 and option #2 in the readme. This was tested on Mac 10.14.6 with Hugo extended v0.74.2. Can you describe any steps to reproduce this issue?

**Comment by onweru** [comment] 2020-07-28 18:42
> to get it to work locally on my mac i had to disable the data integrity lines in baseof.html

@dstamen, please ensure that you've cleared the resources directory. The data integrity ought to work with no issues

**Comment by dstamen** [comment] 2020-07-28 18:46
this is on macos 10.15.6 and hugo 73.0

**Comment by chipzoller** [comment] 2020-07-29 13:24
Closing for now since issue cannot be reproduced on exampleSite content.

**Comment by chipzoller** [comment] 2020-07-29 14:07
Could not reproduce on Mojave with Hugo v0.74.3 and the exampleSite instructions in option 2.

**Closed** 2020-08-04 17:52 UTC
