### ISSUE TITLE
Light/Dark Mode Not Working on Rendered Site

### ISSUE THREAD

**Issue by infosecwar** [chipzoller/hugo-clarity#26] opened 2020-08-31 19:31 UTC
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [X ] Read the README.md
- [X ] Have the extended version of Hugo installed
- [X] Used the exampleSite's config.toml as a reference

**Describe the bug**

Regardless of what browser I use (Firefox, Brave, Edge, etc...) after building and deploying site into production, the toggle switch for Light/Dark mode ceases to work. I have no issue with localhost:1313, but once I upload the files to my server (https://mcalynn.com/), clicking the "sun" (☀) does nothing. No dark mode enabled. 

C:\hugo>hugo env
Hugo Static Site Generator v0.74.3/**extended** windows/amd64 BuildDate: unknown
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.14.3"

C:\hugo\mcalynn>c:\hugo\hugo.exe server -v -w -t hugo-clarity
INFO 2020/08/31 14:06:23 No translation bundle found for default language "en"
INFO 2020/08/31 14:06:23 Translation func for language en not found, use default.
INFO 2020/08/31 14:06:23 i18n not initialized; if you need string translations, check that you have a bundle in /i18n that matches the site language or the default language.
INFO 2020/08/31 14:06:23 Using config file:
Building sites … INFO 2020/08/31 14:06:23 syncing static files to C:\hugo\mcalynn\
WARN 2020/08/31 14:06:23 The []interface {} data from 'menu.yaml' overridden by higher precedence []interface {} data already in the data tree
WARN 2020/08/31 14:06:23 The []interface {} data from 'social.yaml' overridden by higher precedence []interface {} data already in the data tree

                   | EN
-------------------+-----
  Pages            | 60
  Paginator pages  |  1
  Non-page files   |  1
  Static files     | 64
  Processed images |  0
  Aliases          | 32
  Sitemaps         |  1
  Cleaned          |  0

Built in 159 ms
Watching for changes in C:\hugo\mcalynn\{archetypes,content,data,layouts,static,themes}
Watching for config changes in C:\hugo\mcalynn\config.toml, C:\hugo\mcalynn\themes\hugo-clarity\config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

**Comment by onweru** [comment] 2020-08-31 19:50
@infosecwar,

The theme loads a single js script that is fingerprinted. The integrity check fails in your case. https isn't enabled on your site. Yet, you're requesting a https: resource over http. See attached

<img width="1227" alt="Screen Shot 2020-09-01 at 5 46 30 am" src="https://user-images.githubusercontent.com/16350351/91760476-c793a880-ec16-11ea-9b44-090fe4cd19c6.png">

**Comment by infosecwar** [comment] 2020-08-31 19:52
The cert was just installed this morning and verified. I’m making valid HTTPS/SSL connections on my end. (See attached)

Stay safe,
Duncan McAlynn (@infosecwar)

**Comment by infosecwar** [comment] 2020-09-02 18:23
Any other suggestions on this one? Anything else I should try, as SSL/HTTPS connections are clearly happening?

**Comment by onweru** [comment] 2020-09-02 19:29
@infosecwar, there is an integrity issue with the script loaded on your site. Curious how you're generating the production site. `hugo -v` ?

**Comment by infosecwar** [comment] 2020-09-02 21:17
C:\hugo\mcalynn>hugo -v
INFO 2020/09/02 16:15:11 No translation bundle found for default language "en"
INFO 2020/09/02 16:15:11 Translation func for language en not found, use default.
INFO 2020/09/02 16:15:11 i18n not initialized; if you need string translations, check that you have a bundle in /i18n that matches the site language or the default language.
INFO 2020/09/02 16:15:11 Using config file:
Building sites … INFO 2020/09/02 16:15:11 syncing static files to C:\hugo\mcalynn\public\
WARN 2020/09/02 16:15:11 The []interface {} data from 'menu.yaml' overridden by higher precedence []interface {} data already in the data tree
WARN 2020/09/02 16:15:11 The []interface {} data from 'social.yaml' overridden by higher precedence []interface {} data already in the data tree

                   | EN
-------------------+-----
  Pages            | 98
  Paginator pages  |  3
  Non-page files   |  1
  Static files     | 66
  Processed images |  0
  Aliases          | 51
  Sitemaps         |  1
  Cleaned          |  0

Total in 1044 ms

**Comment by infosecwar** [comment] 2020-09-03 20:33
Would this same "single js script that is fingerprinted" also be the reason that the menu won't load on mobile? I just want to know before opening another issue for that problem I'm experiencing as well.

**Comment by onweru** [comment] 2020-09-03 20:59
> Would this same "single js script that is fingerprinted" also be the reason that the menu won't load on mobile? I just want to know before opening another issue for that problem I'm experiencing as well.

That’s right. Until you fix that, several things won’t work, including the menu. At this point I would have to see your repo. From your logs, I can see you’re overriding some stuff. Without seeing what you’re doing I cannot reproduce why your script integrity check is failing on production

**Comment by infosecwar** [comment] 2020-09-03 21:22
I'd love to get to the root cause of this, so whatever I need to do on my end to get it resolved and help others not fall into the same sink hole... just let me know what I need to do. Thanks!

**Comment by onweru** [comment] 2020-09-03 22:05
If you can have your entire local repo on GitHub, I would be happy to play with it and see what's acting up.

**Comment by infosecwar** [comment] 2020-09-03 23:21
Here it is: https://github.com/infosecwar/mcalynn.com

**Comment by onweru** [comment] 2020-09-04 00:46
> https://github.com/infosecwar/mcalynn.com

I will have a looksie and get back to you when I can. Thanks.

**Comment by onweru** [comment] 2020-09-04 01:16
@infosecwar, I have had a look at your repo. You're duplicating your content files on to the [theme/hugo-clarity](https://github.com/infosecwar/mcalynn.com/tree/master/themes/hugo-clarity) directory. It's no wonder the integrity checks fails and your logs have warnings like __"interface {} data from 'menu.yaml' overridden by higher precedence []interface {} data"__. Please keep only themes files inside the `themes/hugo-clarity` directory. In other words, the contents of that directory should be akin to the contents of our repo.

I will refer you back to [this setup section of the README](https://github.com/chipzoller/hugo-clarity#option-1-recommended). Follow those steps religiously and you won't have an issue with the integrity check issue.

I will close this issue because I can adequately confirm that the problem you're experiencing isn't caused by a bug in this theme. It is caused by a fault in your setup. You can leave questions on the thread though; I'll follow up.

<img width="929" alt="Screen Shot 2020-09-03 at 9 11 10 pm" src="https://user-images.githubusercontent.com/16350351/92188279-29782c00-ee2a-11ea-9ee1-558d30d90c28.png">

**Closed by onweru** 2020-09-04 01:16 UTC

**Comment by infosecwar** [comment] 2020-09-04 19:50
Turns out that it was an issue with my FTP client (FileZilla) not maintaining the file integrity. After doing as you said  and cleaning up the directory structure, I was still facing the same issue. When I isolated the file uploads to just the assets/js directory, I noticed that the file sizes we're changing from localhost to the site. Re-upload. Same thing. Only off by a few hundred bytes but enough to fail the integrity check. So, switched to CoreFTP, reuploaded the files and now everything is working as expected. Whew! Leaving this here for others that may run into the same issue. 

Thanks again for your assistance. Without pointing me in the right direction, I doubt I would have got this sorted out. Developer I am not. ;)

**Comment by onweru** [comment] 2020-09-05 02:07
> Turns out that it was an issue with my FTP client (FileZilla) not maintaining the file integrity. After doing as you said and cleaning up the directory structure, I was still facing the same issue. When I isolated the file uploads to just the assets/js directory, I noticed that the file sizes we're changing from localhost to the site. Re-upload. Same thing. Only off by a few hundred bytes but enough to fail the integrity check. So, switched to CoreFTP, reuploaded the files and now everything is working as expected. Whew! Leaving this here for others that may run into the same issue.
> 
> Thanks again for your assistance. Without pointing me in the right direction, I doubt I would have got this sorted out. Developer I am not. ;)

I’m glad you cracked it.
