### ISSUE TITLE
Responsiveness problems on theme (including mobile)

### ISSUE THREAD

**Issue by jmiguelr** [chipzoller/hugo-clarity#164] opened 2021-04-04 09:47 UTC
First of all, thank you for your efforts in this great hugo theme.  

After configuring a new site I've found some issues loading the blog on mobile. I've created a brand new site with default config and problems are also present. 

Default site:
![image](https://user-images.githubusercontent.com/1624675/113504848-40573c00-953b-11eb-854c-07a03ccf6eb3.png)

My own site:
![image](https://user-images.githubusercontent.com/1624675/113504865-64b31880-953b-11eb-9664-1a12393e5ebd.png)

Any workaround to make it work right?

Thank you in advance,

**Comment by chipzoller** [comment] 2021-04-04 12:34
Can you please provide details on your device and browser combination?

**Comment by jmiguelr** [comment] 2021-04-12 09:31
Sorry for delay.  Mobile phone is a Oneplus 5T.   For browser tests I used both Firefox and Chrome. O.S. is Linux. 

Thank you for your reply.

**Comment by atticoder** [comment] 2021-04-19 11:57
The issue is not mobile specific, it is always reproducible with any browser (Edge, Chrome, Firefox) on Windows. The problem is that when menu switches from top bar text menu to popup menu (when window width is too narrow to fit menu texts), the menu will be visible by default and on wrong position (but should be hidden and shown only when clicking menu button).

1. Open page that has top menu
2. By dragging with the mouse make browser window width so small that top menu items do not fit any more. **At this point menu items should only be visible when clicking the menu button, but actually the menu is immediately visible upon creation and is not properly positioned**. In fact, it is not possible hide the menu any more.

Sample menu in config:
```
[menu]

  [[menu.main]]
    id = "products"
    name = "products"
    weight = -100

  [[menu.main]]
    name = "download"
    url = "/download/"
    weight = -60

  [[menu.main]]
    name = "buy"
    url = "/buy/"
    weight = -55

  [[menu.main]]
    name = "support"
    url = "/support/"
    weight = -50
```

**Comment by atticoder** [comment] 2021-04-21 23:19
I found a workaround for the "menu being always visible on small screen" issue by setting the menu to right side in site config (toml):

```
[params]
mobileNavigation = "right"
```
Without this, at present, the web site that use Clarity theme is not usable at all on small-to-medium resolution mobile screen if more than few menu items are used, as total menu items width is then wider than the screen and ghost popup menu that appears on page load blocks entire page.

**Comment by onweru** [comment] 2021-04-22 00:16
This sounds like a bug, the menu should work well irrespective of whether `mobileNavigation` is set to `right` or `left`. I will try to reproduce this and apply a fix soon

**Comment by onweru** [comment] 2021-04-25 17:43
@jmiguelr, @atticoder, this should be decisively fixed now. This was happening whenever `mobileNavigation` wasn't set in [config/_default/paramls.toml](https://github.com/chipzoller/hugo-clarity/blob/70b8924d99d8f995a34465e1a7fed52563a55368/exampleSite/config/_default/params.toml#L45).

**Closed by onweru** 2021-04-25 17:43 UTC
